[package]
name = "failsafe"
version = "0.1.0"
authors = ["Bryan Henry <bryanhenry522@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
chrono = "0.4"
chrono-tz = "0.5"
dotenv = "0.15"
dtparse = "1.2"
enum-iterator = "0.6"
futures = "0.3"
itertools = "0.10"
lazy_static = "1.4"
paste = "1.0"
rand = "0.8"
serde = { version = "1.0", features = ["rc"] }
serde_json = "1.0"
tokio = { version = "1.6", features = ["full"] }
tracing = "0.1"
tracing-subscriber = "0.2"
static_assertions = "1.1"

[dependencies.serenity]
default-features = false
features = ["builder", "cache", "client", "collector", "gateway", "http", "model", "utils", "rustls_backend", "unstable_discord_api"]
# Temporarily build from own fork with not-yet-merged PRs applied
#version = "0.10.8"
git = "https://github.com/sbrocket/serenity.git"
rev = "87b9f04008a322181eae64d7620f57f5244b9c80"
