[package]
name = "failsafe"
version = "0.1.0"
authors = ["Bryan Henry <bryanhenry522@gmail.com>"]
edition = "2018"

[dependencies]
dotenv = "0.15.0"
tokio = { version = "1.6", features = ["full"] }

[dependencies.serenity]
default-features = false
features = ["builder", "cache", "client", "gateway", "http", "model", "utils", "rustls_backend" ]
version = "0.10.7"